### ISSUE TITLE
Migrate older tests to Jasmine 2.0

### ISSUE THREAD

**Issue by hargup** [wurmlab/afra#84]
Some of the js tests in the `master` fails with the error `ReferenceError: waitsFor is not defined`. That is because `waitsFor` [1](http://jasmine.github.io/1.3/introduction.html#section-Asynchronous_Support) which provides Asynchronous support in Jasmine 1.3 is now replaced by an new syntax [2](http://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support) Here are the list of the files that needs a fix. I got them from `git grep "waitsFor"`
- [ ] BAM.spec.js
- [ ] BigWig.spec.js
- [ ] GFF3.spec.js
- [ ] TabixIndex.spec.js
- [ ] TabixIndexedFile.spec.js

**Comment by yeban** [comment]
You had a list of affected test files, right? can you update the issue with those?

**Comment by hargup** [comment]
> You had a list of affected test files, right? can you update the issue with those?

Updated, btw this should be easy to fix.

**Comment by yeban** [comment]
Thanks. It's not necessarily as straightforward. From what I remember, I had found `RemoteBinaryFile.spec.js` to be a bit tricky.

**Comment by proxy-m** [comment]
I see, you delete several functions from Jasmine. But where to find them again? Test example is broken on SO: https://stackoverflow.com/questions/4662641/how-do-i-verify-jquery-ajax-events-with-jasmine/6199132#6199132

**Comment by proxy-m** [comment]
Is upgrade_to_2 guide is still actual? 

https://jasmine.github.io/tutorials/upgrading_to_2

**Comment by proxy-m** [comment]
For some reason it can be rewrited to hard-readable code: 

```
window.getProduct  = function getProduct (id, callback) {
    $.ajax({
        type: "GET",
        url: "data.json",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: callback,
    });
};

it("should make a real AJAX request", function (done) {
    spyOn(window, 'getProduct').and.callThrough(); //create a spy
    var callback = function() {
        expect(getProduct).toHaveBeenCalled(); //use the spy instead of callback
        done();
    };
    getProduct(123, callback);
});

``` 

P.S.: The old code was: 

```
it("should make a real AJAX request", function () {
    var callback = jasmine.createSpy();
    getProduct(123, callback);
    waitsFor(function () {
        return callback.callCount > 0;
    });
    runs(function () {
        expect(callback).toHaveBeenCalled();
    });
});

function getProduct (id, callback) {
    $.ajax({
        type: "GET",
        url: "data.json",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: callback,
    });
}
```
